<?php
/**
 * Posts archive list layout, will set title and use post/list.phtml to render content
 * 
 * @package     Evozon_Blog 
 * @author      Calin Florea <calin.florea@evozon.com>
 * @copyright   Copyright (c) 2015, Evozon
 * @link        http://www.evozon.com  Evozon
 * @see         Evozon_Blog_Block_Post_Archive_Filter
 */
?>
<div class="archive-title">
    <h1><?php echo $this->getHeaderTitle();?></h1>
</div>