<?php
/**
 * this is the template for the image gallery rendering in backend, adminhtml post edit
 * 
 * @package     Evozon_Blog
 * @author      Dana Negrescu <dana.negrescu@evozon.com>
 * @copyright   Copyright (c) 2015, Evozon
 * @link        http://www.evozon.com  Evozon
 * @see         Evozon_Blog_Block_Adminhtml_Post_Edit_Tab_Websites
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('evozon_blog')->__('Posts In Websites') ?></h4>
    </div>
    <fieldset id="grop_fields">
    <div class="store-scope">
        <div class="tree-store-scope">
            <?php foreach ($this->getWebsiteCollection() as $_website): ?>
            <div class="website-name">
                <input name="post[website_ids][]" value="<?php echo $_website->getId() ?>" <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif;?> class="checkbox website-checkbox" id="product_website_<?php echo $_website->getId() ?>" type="checkbox"<?php if($this->hasWebsite($_website->getId())): ?> checked="checked"<?php endif; ?> />
                <big><strong><label for="post_website_<?php echo $_website->getId() ?>"><?php echo $this->escapeHtml($_website->getName()) ?></label></strong></big>
            </div>
            <div class="webiste-groups" id="post_website_<?php echo $_website->getId() ?>_data">
            <?php foreach ($this->getGroupCollection($_website) as $_group): ?>
                <h4><?php echo $this->escapeHtml($_group->getName()) ?></h4>
                <div class="group-stores">
                <table>
                <?php foreach ($this->getStoreCollection($_group) as $_store): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($_store->getName()) ?></td>
                        <td>
                        <?php if($this->getWebsites() && !$this->hasWebsite($_website->getId())): ?>
                            <span class="website-<?php echo $_website->getId() ?>-select" style="display:none">
                            <?php echo Mage::helper('evozon_blog')->__('(Copy data from: %s)', $this->getChooseFromStoreHtml($_store)) ?>
                            </span>
                        <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </table>
                </div>
            <?php endforeach; ?>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
    </fieldset>
</div>
<script type="text/javascript">
//<![CDATA[
    var postWebsiteCheckboxes = $$('.website-checkbox');

    for(var i=0;i<postWebsiteCheckboxes.length;i++){
        Event.observe(postWebsiteCheckboxes[i], 'click', toggleStoreFromChoosers);
    }

    function toggleStoreFromChoosers(event){
        var element = Event.element(event);
        var selects = $('post_website_'+element.value+'_data').getElementsBySelector('select');
        var selectBlocks = $('post_website_'+element.value+'_data').getElementsByClassName('website-'+element.value+'-select');
        for (var i=0; i<selects.length; i++) {
            selects[i].disabled=!element.checked;
        }
        for (var i=0; i<selectBlocks.length; i++) {
            if (element.checked) {
                selectBlocks[i].show();
            }
            else {
                selectBlocks[i].hide();
            }
        }
    }
//]]>
</script>
