<?php
/**
 * Reply form template - comments list
 * 
 * @category   Evozon
 * @package    Evozon_Blog
 * @copyright  Copyright (c) 2015 Evozon (http://www.evozon.com)
 * @author     Andreea Macicasan <andreea.macicasan@evozon.com>
 * @see        Evozon_Blog_Block_Post_View_Comments_Reply
 */
?>

<?php
// get the maximum inputs length from config
$authorMaxLength = (int) $this->getConfig(Evozon_Blog_Model_Config_Validation::VALIDATION_COMMENTS_AUTHOR_MAXLENGTH);
$subjectMaxLength = (int) $this->getConfig(Evozon_Blog_Model_Config_Validation::VALIDATION_COMMENTS_SUBJECT_MAXLENGTH);
$contentMaxLength = (int) $this->getConfig(Evozon_Blog_Model_Config_Validation::VALIDATION_COMMENTS_CONTENT_MAXLENGTH);
$required = (bool) $this->getConfig(Evozon_Blog_Model_Config_Validation::VALIDATION_COMMENTS_SUBJECT_STATUS);
?>

<!--Form for adding a new comment-->
<div class="post_comment_reply" id="post_comment_reply">
    <form class="post_comment_form" id="post_comment_form" action="<?php echo Mage::getUrl('blog/comment/save') ?>" method="post"> 
        <!--Display author data inputs-->
        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <label for="author"><?php echo $this->__('Name'); ?>* :</label>  
            <input id="author" type="text" name="author" class="input-text  required-entry validate-author-max-length maximum-length-<?php echo $authorMaxLength; ?>"/>
            <label for="author_email"><?php echo $this->__('Email'); ?>* :</label>  
            <input id="author_email" type="text" name="author_email" class="input-text required-entry"/>  
        <?php endif; ?>

        <!--Display the subject input-->
        <label for="subject"><?php echo $this->__('Subject'); ?><?php if ($required):?>*<?php endif;?> :</label>  
        <input id="subject" type="text" name="subject" class="input-text <?php if ($required): echo "required-entry"; endif; ?> validate-subject-max-length maximum-length-<?php echo $subjectMaxLength; ?>"/>

        <!--Display the content input-->
        <label for="comment_body"><?php echo $this->__('Comment'); ?>* :</label>  
        <textarea id="content" name="content" class="post_comment_body input-text required-entry validate-content-max-length maximum-length-<?php echo $contentMaxLength; ?>"></textarea>  

        <input type="hidden" name="form_key" id="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
        <input type="hidden" name="parent_id" id="parent_id" value="0"/> 
        <input type="hidden" name="post_id" id="post_id" value="<?php echo $this->getPostId(); ?>"/>

        <div class="required_fields_message">
            <p><?php echo $this->__('Fields marked with "*" are mandatory.'); ?></p>
        </div>

        <!--Add a new comment button-->
        <div class="add_comment">  
            <input class="button" type="button" value="<?php echo $this->__('Add comment'); ?>" id="reply_button" onclick="comment.addComment(this);"/>
        </div>  
    </form>
</div>


<script type='text/javascript'>
Validation.addAllThese([
    ['validate-author-max-length', '<?php echo $this->__('The author name should have maximum %d characters.', (int) $authorMaxLength);  ?>',  function (v, elm) {
        return comment.validateLength(v, elm);
    }],
    ['validate-subject-max-length', '<?php echo $this->__('The subject should have maximum %d characters.', (int) $subjectMaxLength);  ?>',  function (v, elm) {
        return comment.validateLength(v, elm);
    }],
    ['validate-content-max-length', '<?php echo $this->__('The content should have maximum %d characters.', (int) $contentMaxLength);  ?>',  function (v, elm) {
        return comment.validateLength(v, elm);
   }]
]);
</script>
