<?php

/**
 * Blog category related posts shown in main content column.
 *
 * @package     Evozon_Blog
 * @author      Tiberiu Contiu <tiberiu.contiu@evozon.com>
 * @copyright   Copyright (c) 2015, Evozon
 * @link        http://www.evozon.com  Evozon
 */
?>
<?php if ($this->getIsEnabled()) : ?>
<?php $_articlesCollection = $this->getPostsCollection();?>
     <?php if ($_articlesCollection->getSize()): ?>  
        <div class="block block-related block-related-articles">
            <div class="block-title">
                <h2><?php echo $this->__('Featured Posts'); ?></h2>
            </div>
        </div>        
        <div class="category-posts related-articles">
            <ul class="products-grid related-articles-grid">
                <?php foreach ($_articlesCollection as $_article): ?>
                    <?php $imageUrl = (string)$this->getImageHelper()->init($_article, 'small_image')->keepFrame(true)->resize(210); ?>
                    <li class="item">
                        <a href="<?php echo $_article->getPostUrl() ?>" title="<?php echo $this->stripTags($_article->getTitle(), null, true) ?>" class="product-image article-image"><img src="<?php echo $imageUrl; ?>"/></a>
                        <h2 class="product-name article-name"><a href="<?php echo $_article->getPostUrl() ?>" title="<?php echo $this->stripTags($_article->getTitle(), null, true) ?>"><?php echo $_article->getTitle() ?></a></h2>                        
                        <div class="actions">
                            <button type="button" title="<?php echo $this->__('Read More') ?>" class="button" onclick="setLocation('<?php echo $_article->getPostUrl() ?>')"><span><span><?php echo $this->__('Read more') ?></span></span></button>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif;?>
<?php endif;
