<?php
/**
 * This template is used to render the blog post restriction rule's admin UI
 *
 * @package     Evozon_Blog
 * @author      Denis Rendler <denis.rendler@evozon.com>
 * @copyright   Copyright (c) 2015, Evozon
 * @link        http://www.evozon.com  Evozon
 * @see         Evozon_Blog_Block_Adminhtml_Post_Edit_Tab_Restrictions_Renderer_Abstract_Rule
 */
?>
<input
    type="hidden"
    id="<?php echo $this->getTypeInputId(); ?>"
    name="<?php echo $this->getTypeInputName(); ?>"
    value="<?php echo $this->getTypeInputValue(); ?>"
    class="hidden"
    />
<span id="rule-comment"><?php echo $this->getRuleComment() . $this->getRemoveChildElement(); ?></span>