<?php
/**
 * Media tab images template
 * 
 * @category   Evozon
 * @package    Evozon_Blog
 * @copyright  Copyright (c) 2015 Evozon (http://www.evozon.com)
 * @author     Andreea Macicasan <andreea.macicasan@evozon.com>
 * @see        Evozon_Blog_Block_Adminhtml_Post_Helper_Form_Gallery_Content
 */
?>

<?php
$_block = $this;
$_helper = Mage::helper('evozon_blog');
?>
<div id="<?php echo $_block->getHtmlId() ?>" >
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <?php echo $_helper->__('Image type and information need to be specified for each store view.'); ?>
                </li>
            </ul>
        </li>
    </ul>
    <div class="grid">
        <table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid" width="100%">
            <col width="1" />
            <col />
            <col />
            <col width="70" />
            <?php foreach ($_block->getImageTypes() as $typeId => $type): ?>
                <col />
            <?php endforeach; ?>
            <col width="70" />
            <col width="70" />
            <thead>
                <tr class="headings">
                    <th><?php echo $_helper->__('Image') ?></th>
                    <th><?php echo $_helper->__('Label') ?></th>
                    <th><?php echo $_helper->__('Href') ?></th>
                    <th><?php echo $_helper->__('Sort Order') ?></th>
                    <th><?php echo $_helper->__('Post View Image') ?><br/>[<?php echo $_helper->__('STORE VIEW'); ?>]</th>
                    <th><?php echo $_helper->__('Listing Image') ?><br/>[<?php echo $_helper->__('STORE VIEW'); ?>]</th>
                    <th><?php echo $_helper->__('Thumbnail') ?><br/>[<?php echo $_helper->__('STORE VIEW'); ?>]</th>
                    <th><?php echo $_helper->__('Exclude') ?></th>
                    <th class="last"><?php echo $_helper->__('Remove') ?></th>
                </tr>
            </thead>
            <tbody id="<?php echo $_block->getHtmlId() ?>_list">
                <tr id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display">
                    <td class="cell-image">
                        <div class="place-holder" onmouseover="<?php echo $_block->getJsObjectName(); ?>.loadImage('__file__')">
                            <span><?php echo $_helper->__('Roll Over for preview') ?></span>
                        </div>
                        <img src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>" width="100" style="display:none;" alt="" />
                    </td>
                    <td class="cell-label">
                        <input type="text" <?php if ($_block->getElement()->getReadonly()): ?> disabled="disabled"<?php endif; ?> 
                               class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" 
                               onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                    <td class="cell-href">
                        <input type="text" <?php if ($_block->getElement()->getReadonly()): ?> disabled="disabled"<?php endif; ?> 
                               class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" 
                               onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                    <td class="cell-position">
                        <input type="text" <?php if ($_block->getElement()->getReadonly()): ?> disabled="disabled"<?php endif; ?> 
                               class="input-text validate-number" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" 
                               onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                    <?php foreach ($_block->getImageTypes() as $typeId => $type): ?>
                        <td class="cell-<?php echo $typeId ?> a-center">
                            <input <?php if ($_block->getElement()->getAttributeReadonly($typeId)) : ?> disabled="disabled" <?php endif; ?> 
                                   type="radio" name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setPostImages('__file__')" 
                                   value="__file__" />
                        </td>
                    <?php endforeach; ?>
                    <td class="cell-disable a-center">
                        <input type="checkbox" <?php if ($_block->getElement()->getReadonly()): ?> disabled="disabled"<?php endif; ?> 
                               onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                    <td class="cell-remove a-center last">
                        <input type="checkbox" <?php if ($_block->getElement()->getReadonly()): ?> disabled="disabled"<?php endif; ?> 
                               onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                </tr>
                <?php if ($_block->hasUseDefault()): ?>
                    <tr id="<?php echo $_block->getHtmlId() ?>_default">
                        <td><?php echo $_helper->__('Use Default Value') ?></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <?php foreach ($_block->getMediaAttributes() as $_attribute): ?>
                            <td class="a-center">
                                <?php if ($_block->getElement()->canDisplayUseDefault($_attribute)): ?>
                                    <input class="default-checkbox" name="use_default[]" type="checkbox" 
                                        <?php if ($_block->getElement()->getAttributeReadonly($_attribute->getAttributeCode())): ?> disabled="disabled" <?php endif; ?>  
                                        onclick="<?php echo $_block->getJsObjectName(); ?>.updateUseDefault()"
                                        <?php if ($_block->getElement()->usedDefault($_attribute)): ?>checked<?php endif; ?> 
                                        value="<?php echo $_attribute->getAttributeCode() ?>" />
                                <?php endif; ?>
                            </td>
                        <?php endforeach; ?>
                        <td>&nbsp;</td>
                        <td class="last">&nbsp;</td>
                    </tr>
                <?php endif ?>
                <tr id="<?php echo $_block->getHtmlId() ?>-image-0">
                    <td class="cell-image"><?php echo $_helper->__('No image') ?></td>
                    <td class="cell-label"><input type="hidden" />&nbsp;</td>
                    <td class="cell-href"><input type="hidden" />&nbsp;</td>
                    <td class="cell-position"><input type="hidden" />&nbsp;</td>
                    <?php foreach ($_block->getImageTypes() as $typeId => $type): ?>
                        <td class="cell-<?php echo $typeId ?> a-center">
                            <input type="radio" <?php if ($_block->getElement()->getAttributeReadonly($typeId)) : ?> disabled="disabled" <?php endif; ?> 
                                   name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setPostImages('no_selection')" 
                                   value="no_selection" />
                        </td>
                    <?php endforeach; ?>
                    <td class="cell-disable"><input type="hidden" />&nbsp;</td>
                    <td class="cell-remove last"><input type="hidden" />&nbsp;</td>
                </tr>
            </tbody>
            <?php if (!$_block->getElement()->getReadonly()): ?>
                <tfoot>
                    <tr>
                        <td colspan="100" class="last" style="padding:8px">
                            <?php echo $_block->getUploaderHtml() ?>
                        </td>
                    </tr>
                </tfoot>
            <?php endif; ?>
        </table>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="<?php echo $_block->getElement()->getName() ?>[images]" 
       value="<?php echo $_block->escapeHtml($_block->getImagesJson()) ?>" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="<?php echo $_block->getElement()->getName() ?>[values]" 
       value="<?php echo $_block->escapeHtml($_block->getImagesValuesJson()) ?>" />

<script type="text/javascript">
//<![CDATA[
    <?php if (class_exists("Mage_Uploader_Block_Abstract", false)): ?>
        var <?php echo $_block->getJsObjectName(); ?> = new Post.Gallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getImageTypesJson() ?>);
    <?php else: ?>
    var <?php echo $_block->getJsObjectName(); ?> = new Post.Gallery(
        '<?php echo $_block->getHtmlId() ?>',
        <?php if ($_block->getElement()->getReadonly()): ?>null<?php else: ?><?php echo $_block->getUploader()->getJsObjectName() ?><?php endif; ?>,
        <?php echo $_block->getImageTypesJson() ?>
        );
    <?php endif; ?>
//]]>
</script>
